### ISSUE TITLE
TeamsFx Authentication Loop on Mobile Devices

### ISSUE THREAD

**Issue by ZimnitskiYury** [OfficeDev/teams-toolkit#12204] opened 2024-08-09 10:41 UTC
**Description**: In our project, we use TeamsFx and are currently working on the authentication flow. We have followed all the recommended steps from the Microsoft documentation. However, we are encountering an issue on mobile devices (both Android and iPhone).

When a user opens the app on a mobile device, the app cannot silently get a token. To address this, we created a login page that uses teamsFx.login(). This correctly triggers the auth-start from the public folders and displays a page requesting the user to log in and consent to permissions.

The admin must approve the permission request sent from the consent dialog in our tenant. After the user sends the request, they close the dialog using the button inside the dialog. The admin then approves the request. However, when the user starts the app again, all the steps repeat. The user has to log in again and send another request for consent approval.

We have been unable to resolve this issue for a week. All our dependencies use @azure/msal-browser version 2.35, and the same versions are used for auth-start and auth-end.

**Steps to Reproduce:**

Open the app on a mobile device (Android or iPhone).
Attempt to silently get a token (fails).
Redirect to the login page and use teamsFx.login().
Complete the login and consent to permissions.
Admin approves the permission request.
Restart the app and repeat the steps.

**Expected Behavior:** After the admin approves the permission request, the user should be able to start the app without repeating the login and consent steps.

**Actual Behavior:** The user has to log in and send a request for consent approval every time they start the app.

**Environment:**

TeamsFx
@azure/msal-browser version 2.35
Mobile devices (Android and iPhone)

**Comment by KennethBWSong** [comment] 2024-08-12 06:35
Hi @ZimnitskiYury  Thank you for using Teams Toolkit. I cannot reproduce your bug with template "sso tab with fluent ui" which implements the OBO flow. To better understand the error, would you please share some code snippet on how you trigger the login flow?

**Comment by ZimnitskiYury** [comment] 2024-08-12 10:46
@KennethBWSong 

before code some additional notes: 

- admin has no issues with access on mobile phones. issue only on users mobiles.
- on every run of app after invoke teamsCreds.login('.default') user have to login, pass mfa and send request to admin for approve

**First is TeamsContextProvider:** gets teamsContext and passes it to children. nothing complex
```tsx
    export const TeamsContextProvider: React.FC<ITeamsContextProviderProperties> = ({children}) => {
        const teamsContext = useTeamsUserCredential(authConfig);

        const value = React.useMemo(() => {
            const appContext = teamsContext.context as app.Context;
            const tenantId = appContext?.user?.tenant?.id;
            const userId = appContext?.user?.id;
            const chatId = appContext?.chat?.id;
            return {
                ...teamsContext,
                loading: !teamsContext.context,
                themeString: isCommlyticsTheme(teamsContext.themeString) ? teamsContext.themeString : 'default',
                isChat: Boolean(chatId),
                isChannelFocus: Boolean(appContext?.team) || Boolean(appContext?.channel),
                chatId: chatId,
                userGuid: tenantId && userId ? tenantId + '-' + userId : undefined,
            };
        }, [teamsContext]);

        return <TeamsContext.Provider value={value}>{children}</TeamsContext.Provider>;
    };

```

**The next one is AuthProvider:** If teamsUserCredentials has a value, it tries to get a token. On success, it sets isLoading to false, and the authentication flow is finished. On error, it sets isLoading to 'authError', which results in showing the Login page. On the Login page, the user has a button that triggers teamsCreds.login('.default'). After clicking, it shows the Microsoft login page. The user completes MFA and sends a request to the admin for approval. After this, the user clicks a button in the dialog to close it. and this action teamsCreds.login('.default') recognizes as 'consentFailed'. after this user closes our app. admin goes to azure admin portal, approves request and send notification to user. user gets it and opens app again. and all process starts again: token is failed, redirect to Login page, MFA, send request, consentFailed

```tsx
     export const AuthProvider: React.FC<AuthProviderProps> = ({children}) => {
        const {teamsUserCredential} = useTeamsContext();
        const [isLoading, setIsLoading] = React.useState<AuthContextData['isLoading']>(true);

        const handleTryToGetToken = React.useCallback(() => {
            void tryToGetToken(
                teamsUserCredential,
                () => {
                    setIsLoading(false);
                },
                () => {
                    setIsLoading((prev) => (prev === 'consentFailed' ? 'consentFailed' : 'authError'));
                },
            );
        }, [teamsUserCredential]);

        React.useEffect(() => {
            if (!isLoading || !teamsUserCredential) {
                return;
            }

            handleTryToGetToken();
        }, [teamsUserCredential, handleTryToGetToken, isLoading]);

        if (!isLoading || isLoading === 'authError') {
            app.notifySuccess();
        }

        const handleLogin = React.useCallback(() => {
            if (!teamsUserCredential) {
                return;
            }
            void tryToLogin(teamsUserCredential, handleTryToGetToken, (error) => {
                setIsLoading(error);
            });
        }, [teamsUserCredential, handleTryToGetToken]);

        const value: AuthContextData = React.useMemo(() => ({onLogin: handleLogin, isLoading}), [handleLogin, isLoading]);

        return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>;
    };
```

**AuthProvider uses methods:**
```tsx
import {ErrorCode, ErrorWithCode, type TeamsUserCredential} from '@microsoft/teamsfx';
import {logHelper} from 'helpers/logHelper';

const tryToGetToken = async (
    teamsCreds: TeamsUserCredential | undefined,
    onSucess: () => void,
    onError: (error: unknown) => void,
) => {
    if (teamsCreds) {
        try {
            await teamsCreds.getToken('.default');

            onSucess();
        } catch (error) {
            onError(error);
            logHelper.error('Failed to get token', error);
        }
    } else {
        logHelper.error('TeamsUserCredential is not available');
        onError(new Error('TeamsUserCredential is not available'));
    }
};

const tryToLogin = async (
    teamsCreds: TeamsUserCredential | undefined,
    onSucess: () => void,
    onError: (error: 'consentFailed') => void,
) => {
    if (teamsCreds) {
        try {
            await teamsCreds.login('.default');
            onSucess();
        } catch (error: unknown) {
            if (error instanceof ErrorWithCode && error.code === ErrorCode.ConsentFailed) {
                onError('consentFailed');
            }
            logHelper.error('Consent failed', error);
        }
    } else {
        logHelper.error('TeamsUserCredential is not available');
        throw new Error('TeamsUserCredential is not available');
    }
};

export {tryToGetToken, tryToLogin};
```
**Simplified version of LoginPage:**
```tsx
export const Login: React.FC = () => {
    const {toggleIsShown} = useLoggerContext();
    const {onLogin, isLoading} = useAuthContext();
  
    if (isLoading === false) {
        return <Navigate to="tab" />;
    }

    return (
        <div style={{display: 'flex', flexDirection: 'column', gap: '1rem', height: '100%'}}>
                <ErrorPageImage width="300px" />
                {isLoading === 'consentFailed' ? (
                    <>
                        <span
                            style={{
                                fontSize: '28px',
                                marginTop: '20px',
                            }}
                        >
                            Consent process is in progress:
                        </span>
                        <ul style={{paddingLeft: '20px', marginTop: '10px'}}>
                            <li style={{marginBottom: '5px'}}>
                                If you closed the consent dialog without logging in. Please try again.
                            </li>
                            <li>
                                If you requested approval, refresh the page or reopen the app after receiving an email
                                confirmation from your Azure admin.
                            </li>
                        </ul>
                    </>
                ) : (
                    <Text size={400} style={{lineHeight: '1.5', color: '#333'}}>
                        Sign in with your Microsoft account to continue.
                    </Text>
                )}
                <Button appearance="primary" onClick={onLogin}>
                    Sign in with Microsoft
                </Button>
            </div>
        </div>
    );
};
```

**Comment by ZimnitskiYury** [comment] 2024-08-12 10:50
additional screenshots: 
_used azure/msal-browser_
![image](https://github.com/user-attachments/assets/04137bf1-c24b-4446-a935-cfddb98711cf)

_deps:_
![image](https://github.com/user-attachments/assets/5787d185-01fc-4d11-b490-6d2bb5da2720)

_auth-start_
```html
<!--This file is used during the Teams authentication flow to assist with retrieval of the access token.-->
<!--If you're not familiar with this, do not alter or remove this file from your project.-->
<html>
  <head>
    <title>Login Start Page</title>
    <meta charset="utf-8" />
  </head>

  <body>
    <script
      type="text/javascript"
      src="https://res.cdn.office.net/teams-js/2.22.0/js/MicrosoftTeams.min.js"
      integrity="sha384-WSG/sWulIv7rel5TnFlH8JTpxl2OxzZh9Lux2mIzBFiTRLFvMBeFv9VURu/3vQdx"
      crossorigin="anonymous"
    ></script>
    <script
      type="text/javascript"
      src="https://alcdn.msauth.net/browser/2.35.0/js/msal-browser.min.js"
      integrity="sha384-PARf28kmic36Ve+O3DnUerRXFtOQ7ZDqRDGpLcbljly5/N39T2OV3kt3QsWOKeAX"
      crossorigin="anonymous"
    ></script>
    <script type="text/javascript">
      microsoftTeams.app.initialize().then(() => {
        // Get the tab context, and use the information to navigate to Azure AD login page
        microsoftTeams.getContext(async function (context) {
          // Generate random state string and store it, so we can verify it in the callback
          var currentURL = new URL(window.location);
          var clientId = currentURL.searchParams.get("clientId");
          var scope = currentURL.searchParams.get("scope");
          var loginHint = currentURL.searchParams.get("loginHint");

          const msalConfig = {
            auth: {
              clientId: clientId,
              authority: `https://login.microsoftonline.com/${context.tid}`,
              navigateToLoginRequestUrl: false,
            },
            cache: {
              cacheLocation: "sessionStorage",
            },
          };

          const msalInstance = new msal.PublicClientApplication(msalConfig);
          const scopesArray = scope.split(" ");
          const scopesRequest = {
            scopes: scopesArray,
            redirectUri: window.location.origin + `/auth-end.html?clientId=${clientId}`,
            loginHint: loginHint,
            prompt: "consent",
          };

          await msalInstance.loginRedirect(scopesRequest);
        });
      });
    </script>
  </body>
</html>
```

_auth-end_
```html
<!--This file is used during the Teams authentication flow to assist with retrieval of the access token.-->
<!--If you're not familiar with this, do not alter or remove this file from your project.-->
<html>
  <head>
    <title>Login End Page</title>
    <meta charset="utf-8" />
  </head>

  <body>
    <script
      type="text/javascript"
      src="https://res.cdn.office.net/teams-js/2.22.0/js/MicrosoftTeams.min.js"
      integrity="sha384-WSG/sWulIv7rel5TnFlH8JTpxl2OxzZh9Lux2mIzBFiTRLFvMBeFv9VURu/3vQdx"
      crossorigin="anonymous"
    ></script>
    <script
      type="text/javascript"
      src="https://alcdn.msauth.net/browser/2.35.0/js/msal-browser.min.js"
      integrity="sha384-PARf28kmic36Ve+O3DnUerRXFtOQ7ZDqRDGpLcbljly5/N39T2OV3kt3QsWOKeAX"
      crossorigin="anonymous"
    ></script>
    <script type="text/javascript">
      var currentURL = new URL(window.location);
      var clientId = currentURL.searchParams.get("clientId");

      microsoftTeams.app.initialize().then(() => {
        microsoftTeams.getContext(async function (context) {
          const msalConfig = {
            auth: {
              clientId: clientId,
              authority: `https://login.microsoftonline.com/${context.tid}`,
              navigateToLoginRequestUrl: false,
            },
            cache: {
              cacheLocation: "sessionStorage",
            },
          };

          const msalInstance = new window.msal.PublicClientApplication(msalConfig);
          msalInstance
            .handleRedirectPromise()
            .then((tokenResponse) => {
              if (tokenResponse !== null) {
                microsoftTeams.authentication.notifySuccess(
                  JSON.stringify({
                    sessionStorage: sessionStorage,
                  }),
                );
              } else {
                microsoftTeams.authentication.notifyFailure("Get empty response.");
              }
            })
            .catch((error) => {
              microsoftTeams.authentication.notifyFailure(JSON.stringify(error));
            });
        });
      });
    </script>
  </body>
</html>
```

**Comment by ZimnitskiYury** [comment] 2024-08-12 16:19
removing `prompt: "consent"` fixed issue. ticket can be closed.

**Comment by KennethBWSong** [comment] 2024-08-15 01:30
Closed as solved.

**Closed by KennethBWSong** 2024-08-15 01:30 UTC
Labels: investigating, TA:Auth, needs attention
