### ISSUE TITLE
React with Fluent UI Tab Error: 

### ISSUE THREAD

**Issue by ThomasPe** [OfficeDev/teams-toolkit#12261] opened 2024-08-21 21:02 UTC
**Describe the bug**
A newly created Tab => React with Fluent UI => TypeScript results in the following error when running the app without any other changes:

```
WARNING in ./node_modules/@fluentui/react-window-provider/lib/WindowProvider.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Code\temp\fluenttest\node_modules\@fluentui\react-window-provider\src\WindowProvider.tsx' file: Error: ENOENT: no such file or directory, open 'C:\Code\temp\fluenttest\node_modules\@fluentui\react-window-provider\src\WindowProvider.tsx'

WARNING in ./node_modules/@fluentui/react-window-provider/lib/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Code\temp\fluenttest\node_modules\@fluentui\react-window-provider\src\index.ts' file: Error: ENOENT: no such file or directory, open 'C:\Code\temp\fluenttest\node_modules\@fluentui\react-window-provider\src\index.ts'

WARNING in ./node_modules/@fluentui/react-window-provider/lib/version.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Code\temp\fluenttest\node_modules\@fluentui\react-window-provider\src\version.ts' file: Error: ENOENT: no such file or directory, open 'C:\Code\temp\fluenttest\node_modules\@fluentui\react-window-provider\src\version.ts'
```

I've tried it twice with the same result. Also on a different PC.

**VS Code Extension Information (please complete the following information):**
 - OS: Windows
 - Version v5.8.1

**CLI Information (please complete the following information):**
 - OS: Windows
 - Version 3.0.2

**Comment by Yimin-Jin** [comment] 2024-08-22 06:37
We apologize for the inconvenience caused by this warning log. Please note that it is a warning-level log and does not prevent the app from starting. We are actively working on resolving this issue and expect to release a fix in the upcoming pre-release.

**Comment by Yimin-Jin** [comment] 2024-08-28 06:55
> Im facing the same error and it's not loading the app for me!

Could you please provide the error logs? From our side, the warning logs you mentioned do not seem to prevent the Teams app from starting.

**Comment by Yimin-Jin** [comment] 2024-09-05 04:00
We have fixed this bug and will release it in the next prerelease.
[https://github.com/OfficeDev/teams-toolkit/pull/12332](url)

**Comment by redlab-chris** [comment] 2024-10-14 19:47
The same warnings are generated when using Fluent UI v8 (8.121.4) in my project in combination with web pack and source-map-loader.

WARNING in ./node_modules/@fluentui/react-window-provider/lib/WindowProvider.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C...\node_modules\@fluentui\react-window-provider\src\WindowProvider.tsx' file: Error: ENOENT: no such file or directory, open 'C:...\node_modules\@fluentui\react-window-provider\src\WindowProvider.tsx'

WARNING in ./node_modules/@fluentui/react-window-provider/lib/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\...\node_modules\@fluentui\react-window-provider\src\index.ts' file: Error: ENOENT: no such file or directory, open 'C:\...\node_modules\@fluentui\react-window-provider\src\index.ts'

WARNING in ./node_modules/@fluentui/react-window-provider/lib/version.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\...\node_modules\@fluentui\react-window-provider\src\version.ts' file: Error: ENOENT: no such file or directory, open 'C:\...\node_modules\@fluentui\react-window-provider\src\version.ts'

It looks like an issue in the 3 .js.map files in folder ..\node_modules\@fluentui\react-window-provider\lib.
These source maps contain references to typescript source files (.ts, tsx) but the source files are javascript files (e.g. WindowProvider.js) and thus cannot be found by the source-map-loader. 

The references to package react-window-provider are like this in my project.

├─┬ @fluentui/react@8.121.4
│ ├─┬ @fluentui/react-hooks@8.8.16
│ │ └── @fluentui/react-window-provider@2.2.28 deduped
│ └── @fluentui/react-window-provider@2.2.28
└─┬ @fluentui/utilities@8.15.19
  └── @fluentui/react-window-provider@2.2.28 deduped

adding this to the webpack.config.js helps ;)

ignoreWarnings: [/Failed to parse source map/],

**Comment by Yimin-Jin** [comment] 2024-10-21 03:11
> The same warnings are generated when using Fluent UI v8 (8.121.4) in my project in combination with web pack and source-map-loader.
> 
> WARNING in ./node_modules/@fluentui/react-window-provider/lib/WindowProvider.js Module Warning (from ./node_modules/source-map-loader/dist/cjs.js): Failed to parse source map from 'C...\node_modules@fluentui\react-window-provider\src\WindowProvider.tsx' file: Error: ENOENT: no such file or directory, open 'C:...\node_modules@fluentui\react-window-provider\src\WindowProvider.tsx'
> 
> WARNING in ./node_modules/@fluentui/react-window-provider/lib/index.js Module Warning (from ./node_modules/source-map-loader/dist/cjs.js): Failed to parse source map from 'C:...\node_modules@fluentui\react-window-provider\src\index.ts' file: Error: ENOENT: no such file or directory, open 'C:...\node_modules@fluentui\react-window-provider\src\index.ts'
> 
> WARNING in ./node_modules/@fluentui/react-window-provider/lib/version.js Module Warning (from ./node_modules/source-map-loader/dist/cjs.js): Failed to parse source map from 'C:...\node_modules@fluentui\react-window-provider\src\version.ts' file: Error: ENOENT: no such file or directory, open 'C:...\node_modules@fluentui\react-window-provider\src\version.ts'
> 
> It looks like an issue in the 3 .js.map files in folder ..\node_modules@fluentui\react-window-provider\lib. These source maps contain references to typescript source files (.ts, tsx) but the source files are javascript files (e.g. WindowProvider.js) and thus cannot be found by the source-map-loader.
> 
> The references to package react-window-provider are like this in my project.
> 
> ├─┬ @fluentui/react@8.121.4 │ ├─┬ @fluentui/react-hooks@8.8.16 │ │ └── @fluentui/react-window-provider@2.2.28 deduped │ └── @fluentui/react-window-provider@2.2.28 └─┬ @fluentui/utilities@8.15.19 └── @fluentui/react-window-provider@2.2.28 deduped
> 
> adding this to the webpack.config.js helps ;)
> 
> ignoreWarnings: [/Failed to parse source map/],

You can check if your project uses react-scripts. If it does, our suggested solution is to replace `react-scripts` with `vite`. You can refer to this PR for more details: [migrate react-script to vite](https://github.com/OfficeDev/teams-toolkit/pull/12332).

**Closed** 2024-12-26 02:56 UTC
Labels: bug, investigating, needs more info, TA:Compute, no recent activity
