### ISSUE TITLE
bug report: AppStudioPlugin.TeamsAppUpdateFailed

### ISSUE THREAD

**Issue by masato-e** [OfficeDev/teams-toolkit#12092] opened 2024-07-29 01:46 UTC
Unable to update Teams app with ID aba5820c-1750-485e-a90a-1530c2ff2b59 in Teams Developer Portal due to Unable to make API call to Developer Portal: AxiosError, Request failed with status code 422, API name: create-app, X-Correlation-ID: 9cfa7cb2-b98c-4dde-b466-40575f81dacd. This may be due to a temporary service error. Try again after a few minutes. data: "Error while updating assets to the blob storage for tenant id f9a73505-c962-44e3-b699-9ea9cf8ff7a5, appDefinitionId aba5820c-1750-485e-a90a-1530c2ff2b59. Error message: Error while deleting assets from the blob storage for tenant id f9a73505-c962-44e3-b699-9ea9cf8ff7a5, appDefinitionId aba5820c-1750-485e-a90a-1530c2ff2b59. Error message: Key based authentication is not permitted on this storage account."

stack:
TeamsAppUpdateFailed: Unable to update Teams app with ID aba5820c-1750-485e-a90a-1530c2ff2b59 in Teams Developer Portal due to Unable to make API call to Developer Portal: AxiosError, Request failed with status code 422, API name: create-app, X-Correlation-ID: 9cfa7cb2-b98c-4dde-b466-40575f81dacd. This may be due to a temporary service error. Try again after a few minutes. data: "Error while updating assets to the blob storage for tenant id f9a73505-c962-44e3-b699-9ea9cf8ff7a5, appDefinitionId aba5820c-1750-485e-a90a-1530c2ff2b59. Error message: Error while deleting assets from the blob storage for tenant id f9a73505-c962-44e3-b699-9ea9cf8ff7a5, appDefinitionId aba5820c-1750-485e-a90a-1530c2ff2b59. Error message: Key based authentication is not permitted on this storage account."
	at AppStudioResultFactory.SystemError (<REDACTED: user-file-path>/extension.js:2:610777)
	at ConfigureTeamsAppDriver.update (<REDACTED: user-file-path>/extension.js:2:562630)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async ConfigureTeamsAppDriver.<anonymous> (<REDACTED: user-file-path>/extension.js:2:492921)
	at async ConfigureTeamsAppDriver.execute (<REDACTED: user-file-path>/extension.js:2:560214)
	at async Lifecycle.executeImpl (<REDACTED: user-file-path>/extension.js:2:232111)
	at async Lifecycle.execute (<REDACTED: user-file-path>/extension.js:2:229268)
	at async Coordinator.publish (<REDACTED: user-file-path>/extension.js:2:279139)
	at async Coordinator.<anonymous> (<REDACTED: user-file-path>/extension.js:2:1045956)
	at async FxCore.publishApplication (<REDACTED: user-file-path>/extension.js:2:968016)
	at async exports.EnvWriterMW (<REDACTED: user-file-path>/extension.js:2:871186)
	at async exports.ContextInjectorMW (<REDACTED: user-file-path>/extension.js:2:1049708)
	at async exports.ConcurrentLockerMW (<REDACTED: user-file-path>/extension.js:2:1048659)
	at async envLoaderMWImpl (<REDACTED: user-file-path>/extension.js:2:871066)
	at async FxCore.<anonymous> (<REDACTED: user-file-path>/extension.js:2:869964)
	at async exports.ProjectMigratorMWV3 (<REDACTED: user-file-path>/extension.js:2:1080366)
	at async exports.ErrorHandlerMW (<REDACTED: user-file-path>/extension.js:2:1050205)
	at async FxCore.<anonymous> (<REDACTED: user-file-path>/extension.js:2:1045956)

**Comment by HuihuiWu-Microsoft** [comment] 2024-07-29 02:34
Thanks for your feedback! We're working with service team to fix the error and will keep you updated.

**Comment by HuihuiWu-Microsoft** [comment] 2024-07-29 05:12
@masato-e  Service has been recovered, please retry and check if the issue still exists.

**Comment by leonardjohn** [comment] 2024-07-29 05:33
Indeed, it works fine now.

**Comment by andres-swax** [comment] 2024-07-29 14:22
> @masato-e Service has been recovered, please retry and check if the issue still exists.

Good morning, given the disruptive nature of the issue it would be great if:
- Some background information on the issue is provided. In particular, confirmation that there is some backend "piping" to the provisioning actions so we know for certain that there are failure points beyond our control.
- How can one easily tell whether this or a similar issue is taking place so we can avoid spending hours debugging our code. The number of hours multiplied the number of people who actually debugged or tried to debug this adds to a lot of work for nothing.
- Is there anything that can be done to shield the backend (if it exists) error messages from the actions being called? There was one message stating "this may be an internal problem try later" or something like that. That was super-extremely unhelpful and introduced more confusion to the whole situation.
Lastly the Teams Toolkit is great and is getting a lot of attention and becoming widely adopted. Thank you all for that.

**Comment by HuihuiWu-Microsoft** [comment] 2024-07-30 03:02
Hi @masato-e 

- The issue is introduced by App Studio service team when deploying new changes without setting feature flag correctly. We raised ICM ticket to related team at our first notice.
- Service side issues could happen. You may create another app to see whether same errors exist or check in our GitHub issues to see whether others are encountering the same issue. We have setup a flow to monitor service API call failures and will notify service team to avoid high impact to users. But that was broken by recent security updates hence we failed to notice the problem at first time. We're actively working on it and will recover soon.
- The backend might be unstable sometimes and the error message indicates user to retry to avoid possible failure due to network or other issues. Do you have any suggestion on this?

**Comment by andres-swax** [comment] 2024-07-30 05:50
> * The backend might be unstable sometimes and the error message indicates user to retry to avoid possible failure due to network or other issues. Do you have any suggestion on this?

TBH it would be better for devs not to see the internal backend problems, but at the same time it is good to see that so devs can report the issue with as much information as possible helping debug. I do believe maybe it's better just to report backend issue try later but I'm not experienced enough handling big libraries such as this, so, just an idea.  Thanks for the update/feedback, makes things clear and seems there is now a process to "keep an eye" on the backend.

**Comment by adashen** [comment] 2024-07-30 05:52
Thanks for the suggestion. As the issue is resolved close it now.

**Closed by adashen** 2024-07-30 05:52 UTC
Labels: bug, needs attention
