### ISSUE TITLE
bug report: AppStudioPlugin.TeamsAppPublishConflict

### ISSUE THREAD

**Issue by raymondilife** [OfficeDev/teams-toolkit#12760] opened 2024-11-20 04:25 UTC
Unable to publish Teams app because Teams app with this ID already exists in staged apps. Update the app ID and try again. fd23b66f-8ed4-418a-8a96-38f1207c2240

stack:
TeamsAppPublishConflict: Unable to publish Teams app because Teams app with this ID already exists in staged apps. Update the app ID and try again. fd23b66f-8ed4-418a-8a96-38f1207c2240
	at utt.SystemError (<REDACTED: user-file-path>/extension.js:209:3686)
	at Fv.publishTeamsApp (<REDACTED: user-file-path>/extension.js:213:25920)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async Fv.<anonymous> (<REDACTED: user-file-path>/extension.js:14:389775)
	at async j9t.publish (<REDACTED: user-file-path>/extension.js:768:13869)
	at async j9t.<anonymous> (<REDACTED: user-file-path>/extension.js:596:26429)
	at async j9t.execute (<REDACTED: user-file-path>/extension.js:768:11608)
	at async e.executeImpl (<REDACTED: user-file-path>/extension.js:630:4660)
	at async e.execute (<REDACTED: user-file-path>/extension.js:630:2382)
	at async Ure.publish (<REDACTED: user-file-path>/extension.js:744:17599)
	at async Ure.<anonymous> (<REDACTED: user-file-path>/extension.js:14:389775)
	at async If.publishApplication (<REDACTED: user-file-path>/extension.js:849:25668)
	at async If.K3c (<REDACTED: user-file-path>/extension.js:812:16106)
	at async If.l7c (<REDACTED: user-file-path>/extension.js:812:20373)
	at async If.c7c (<REDACTED: user-file-path>/extension.js:812:19427)
	at async J3c (<REDACTED: user-file-path>/extension.js:812:16078)
	at async If.<anonymous> (<REDACTED: user-file-path>/extension.js:812:15243)
	at async If.rAc (<REDACTED: user-file-path>/extension.js:847:6474)
	at async If.p7c (<REDACTED: user-file-path>/extension.js:812:20672)
	at async If.<anonymous> (<REDACTED: user-file-path>/extension.js:14:389775)
	at async pw (<REDACTED: user-file-path>/extension.js:1690:18215)
	at async Object.xba [as callback] (<REDACTED: user-file-path>/extension.js:1712:17044)
	at async e.runCommand (<REDACTED: user-file-path>/extension.js:1690:15449)
	at async Y0.h (file:///c:/Users/20140014/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:32825)
	at async Y0.h (file:///c:/Users/20140014/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:32825)

**Comment by anchenyi** [comment] 2024-11-20 06:43
hi @raymondilife, this issue is a duplicate of #12421 . Please check that for a solution. Thanks!

**Comment by adashen** [comment] 2024-11-21 06:06
close as duplicate

**Closed by adashen** 2024-11-21 06:06 UTC
Labels: investigating, TA:E2E, needs attention
